# Generated by Django 6.0.6 on 2026-06-27 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='企业名称')),
                ('main_business', models.TextField(blank=True, verbose_name='主营业务')),
                ('service_regions', models.CharField(blank=True, max_length=255, verbose_name='服务地区')),
                ('max_project_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='可承接最高金额')),
                ('forbidden_conditions', models.TextField(blank=True, verbose_name='禁投条件')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '企业能力档案',
                'verbose_name_plural': '企业能力档案',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='项目名称')),
                ('industry', models.CharField(blank=True, max_length=120, verbose_name='所属行业')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='合同金额')),
                ('client_name', models.CharField(blank=True, max_length=160, verbose_name='客户名称')),
                ('completed_at', models.DateField(blank=True, null=True, verbose_name='完成日期')),
                ('description', models.TextField(blank=True, verbose_name='项目说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='tenders.companyprofile', verbose_name='所属企业')),
            ],
            options={
                'verbose_name': '历史业绩',
                'verbose_name_plural': '历史业绩',
                'ordering': ['company__name', '-completed_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='资质名称')),
                ('certificate_no', models.CharField(blank=True, max_length=120, verbose_name='证书编号')),
                ('issuer', models.CharField(blank=True, max_length=160, verbose_name='发证机构')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='有效期至')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='tenders.companyprofile', verbose_name='所属企业')),
            ],
            options={
                'verbose_name': '资质证书',
                'verbose_name_plural': '资质证书',
                'ordering': ['company__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TenderProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220, verbose_name='项目名称')),
                ('procurement_method', models.CharField(blank=True, max_length=80, verbose_name='采购方式')),
                ('project_type', models.CharField(blank=True, max_length=80, verbose_name='项目类型')),
                ('region', models.CharField(blank=True, max_length=120, verbose_name='项目地区')),
                ('budget_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='预算金额')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='投标截止时间')),
                ('source_text', models.TextField(blank=True, verbose_name='招标文本')),
                ('status', models.CharField(choices=[('pending', '待分析'), ('analyzing', '分析中'), ('analyzed', '已分析'), ('recommended', '推荐报名'), ('abandoned', '已放弃'), ('archived', '已归档')], default='pending', max_length=32, verbose_name='项目状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tender_projects', to='tenders.companyprofile', verbose_name='匹配企业')),
            ],
            options={
                'verbose_name': '招标项目',
                'verbose_name_plural': '招标项目',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('recommended', '推荐投标'), ('cautious', '谨慎投标'), ('not_recommended', '不建议投标'), ('needs_review', '人工复核')], max_length=32, verbose_name='投标建议')),
                ('match_score', models.PositiveSmallIntegerField(default=0, verbose_name='匹配评分')),
                ('summary', models.TextField(blank=True, verbose_name='报告摘要')),
                ('risks', models.JSONField(blank=True, default=list, verbose_name='风险清单')),
                ('missing_materials', models.JSONField(blank=True, default=list, verbose_name='缺失材料')),
                ('next_actions', models.JSONField(blank=True, default=list, verbose_name='下一步动作')),
                ('raw_report', models.JSONField(blank=True, default=dict, verbose_name='智能体原始报告')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('tender_project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_report', to='tenders.tenderproject', verbose_name='招标项目')),
            ],
            options={
                'verbose_name': 'AI分析报告',
                'verbose_name_plural': 'AI分析报告',
                'ordering': ['-created_at'],
            },
        ),
    ]
