# Generated by Django 6.0.6 on 2026-06-27 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenderDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='tender_documents/', verbose_name='PDF文件')),
                ('original_name', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='文件大小')),
                ('parse_status', models.CharField(choices=[('pending', '待解析'), ('parsed', '已解析'), ('failed', '解析失败')], default='pending', max_length=32, verbose_name='解析状态')),
                ('extracted_text', models.TextField(blank=True, verbose_name='提取文本')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('tender_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='tenders.tenderproject', verbose_name='招标项目')),
            ],
            options={
                'verbose_name': '招标文件',
                'verbose_name_plural': '招标文件',
                'ordering': ['-created_at'],
            },
        ),
    ]
