# Generated by Django 6.0.6 on 2026-06-27 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0002_tenderdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('follow_up', '跟进记录'), ('risk', '风险说明'), ('decision', '决策记录'), ('material', '材料补充'), ('status', '状态变更'), ('system', '系统记录')], default='follow_up', max_length=32, verbose_name='记录类型')),
                ('content', models.TextField(verbose_name='记录内容')),
                ('operator_name', models.CharField(blank=True, default='系统', max_length=80, verbose_name='操作人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('tender_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='tenders.tenderproject', verbose_name='招标项目')),
            ],
            options={
                'verbose_name': '项目处理记录',
                'verbose_name_plural': '项目处理记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
