# Generated by Django 6.0.6 on 2026-06-27 17:28

from django.db import migrations, models


def seed_tender_references(apps, schema_editor):
    TenderReference = apps.get_model('tenders', 'TenderReference')
    samples = [
        {
            'title': '智慧园区数字化平台建设参考标书',
            'project_type': '软件信息化',
            'industry': '园区数字化',
            'region': '江苏',
            'issuing_organization': '某高新区管理委员会',
            'budget_amount': 4800000,
            'published_at': '2026-03-15',
            'summary': '覆盖需求分析、平台架构、实施计划和运维要求，适合软件平台类项目参考。',
            'reference_points': '重点关注技术评分、项目经理资历、驻场服务、验收里程碑。',
            'source_text': '第一章 招标公告\n第二章 投标人须知\n第三章 技术规范书\n第四章 评分办法\n第五章 商务条款',
            'tags': '智慧园区、数字平台、软件实施',
            'is_featured': True,
        },
        {
            'title': '电子政务云平台扩容项目参考标书',
            'project_type': '云平台建设',
            'industry': '政务信息化',
            'region': '上海',
            'issuing_organization': '某市大数据中心',
            'budget_amount': 9200000,
            'published_at': '2026-02-08',
            'summary': '适合参考云资源扩容、等保整改、迁移切换和运维服务条款。',
            'reference_points': '重点关注SLA、等保三级、资源池配额、应急演练和驻场工程师要求。',
            'source_text': '第一章 项目概况\n第二章 云资源与安全要求\n第三章 运维及响应机制\n第四章 评分细则',
            'tags': '政务云、扩容、运维服务',
            'is_featured': True,
        },
        {
            'title': '校园弱电系统改造工程参考标书',
            'project_type': '弱电集成',
            'industry': '教育信息化',
            'region': '浙江',
            'issuing_organization': '某职业技术学院',
            'budget_amount': 2650000,
            'published_at': '2025-12-20',
            'summary': '适合参考综合布线、监控门禁、广播网络和施工组织要求。',
            'reference_points': '重点关注施工周期、人员持证要求、售后巡检和材料品牌约束。',
            'source_text': '第一章 工程概况\n第二章 施工技术要求\n第三章 材料设备清单\n第四章 商务响应表',
            'tags': '弱电、校园、施工组织',
            'is_featured': False,
        },
    ]

    for sample in samples:
        TenderReference.objects.update_or_create(
            title=sample['title'],
            defaults=sample,
        )


def unseed_tender_references(apps, schema_editor):
    TenderReference = apps.get_model('tenders', 'TenderReference')
    TenderReference.objects.filter(
        title__in=[
            '智慧园区数字化平台建设参考标书',
            '电子政务云平台扩容项目参考标书',
            '校园弱电系统改造工程参考标书',
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0003_projectnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenderReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220, verbose_name='参考标书名称')),
                ('project_type', models.CharField(blank=True, max_length=120, verbose_name='项目类型')),
                ('industry', models.CharField(blank=True, max_length=120, verbose_name='所属行业')),
                ('region', models.CharField(blank=True, max_length=120, verbose_name='适用地区')),
                ('issuing_organization', models.CharField(blank=True, max_length=180, verbose_name='招标单位')),
                ('budget_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='预算金额')),
                ('published_at', models.DateField(blank=True, null=True, verbose_name='发布日期')),
                ('summary', models.TextField(blank=True, verbose_name='内容摘要')),
                ('reference_points', models.TextField(blank=True, verbose_name='参考要点')),
                ('source_text', models.TextField(blank=True, verbose_name='标书正文')),
                ('tags', models.CharField(blank=True, max_length=255, verbose_name='标签')),
                ('is_featured', models.BooleanField(default=True, verbose_name='重点参考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '参考标书',
                'verbose_name_plural': '参考标书',
                'ordering': ['-is_featured', '-published_at', '-updated_at'],
            },
        ),
        migrations.RunPython(seed_tender_references, unseed_tender_references),
    ]
