# Generated by Django 6.0.6 on 2026-06-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0004_tenderreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_info', models.TextField(blank=True, verbose_name='基础信息')),
                ('tender_content', models.TextField(blank=True, verbose_name='标书内容')),
                ('reference_points', models.TextField(blank=True, verbose_name='参考要点')),
                ('scoring_rules', models.TextField(blank=True, verbose_name='评分规则')),
                ('risk_tags', models.TextField(blank=True, verbose_name='风险标签')),
                ('material_checklist', models.TextField(blank=True, verbose_name='材料清单')),
                ('source_maintenance_info', models.TextField(blank=True, verbose_name='来源与维护信息')),
            ],
            options={
                'verbose_name': '合同参考',
                'verbose_name_plural': '合同参考',
                'db_table': 'contract',
                'ordering': ['-id'],
            },
        ),
    ]
