# Generated by Codex on 2026-06-28

from django.db import migrations


def seed_contracts(apps, schema_editor):
    Contract = apps.get_model('tenders', 'Contract')
    rows = [
        {
            'basic_info': '智慧园区数字化平台建设项目\n采购方式：公开招标\n预算金额：480万元\n适用地区：江苏',
            'tender_content': '建设统一园区数字底座、企业服务门户、招商管理模块和可视化驾驶舱，要求12个月内完成上线与验收。',
            'reference_points': '重点参考项目经理资历、驻场团队配置、原厂授权函、近三年同类案例。',
            'scoring_rules': '技术分50分，商务分30分，价格分20分。技术方案完整性和实施案例是核心得分点。',
            'risk_tags': '原厂授权风险\n付款周期偏长\n异地驻场压力',
            'material_checklist': '营业执照\nISO9001\nCMMI三级\n原厂授权函\n同类案例合同扫描件',
            'source_maintenance_info': '来源：园区数字化类历史项目\n维护人：经营管理部\n最近更新：2026-06-28',
        },
        {
            'basic_info': '电子政务云平台扩容项目\n采购方式：竞争性磋商\n预算金额：920万元\n适用地区：上海',
            'tender_content': '扩容现有政务云资源池，完善容灾、监控、日志审计和运维响应机制，要求满足等保三级。',
            'reference_points': '重点参考云资源清单、SLA条款、等保合规要求、迁移窗口和割接预案。',
            'scoring_rules': '技术分55分，运维与保障分25分，商务价格分20分。等级保护和运维能力权重较高。',
            'risk_tags': '等保合规风险\n割接失败风险\n7x24运维承诺压力',
            'material_checklist': '云厂商资质\n运维团队简历\n等保测评报告\n应急预案\nSLA响应承诺',
            'source_maintenance_info': '来源：政务云扩容项目归档\n维护人：售前解决方案组\n最近更新：2026-06-28',
        },
    ]

    for row in rows:
        Contract.objects.get_or_create(
            basic_info=row['basic_info'],
            defaults=row,
        )


def unseed_contracts(apps, schema_editor):
    Contract = apps.get_model('tenders', 'Contract')
    Contract.objects.filter(
        basic_info__in=[
            '智慧园区数字化平台建设项目\n采购方式：公开招标\n预算金额：480万元\n适用地区：江苏',
            '电子政务云平台扩容项目\n采购方式：竞争性磋商\n预算金额：920万元\n适用地区：上海',
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0005_contract'),
    ]

    operations = [
        migrations.RunPython(seed_contracts, unseed_contracts),
    ]
