# Generated by Django 6.0.6 on 2026-07-13 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def add_owner_column(apps, schema_editor):
    table_name = 'tenders_companyprofile'
    with schema_editor.connection.cursor() as cursor:
        columns = {
            column.name
            for column in schema_editor.connection.introspection.get_table_description(cursor, table_name)
        }
    if 'owner_id' not in columns:
        schema_editor.execute(f'ALTER TABLE {table_name} ADD COLUMN owner_id bigint NULL')


def remove_owner_column(apps, schema_editor):
    table_name = 'tenders_companyprofile'
    with schema_editor.connection.cursor() as cursor:
        columns = {
            column.name
            for column in schema_editor.connection.introspection.get_table_description(cursor, table_name)
        }
    if 'owner_id' in columns:
        schema_editor.execute(f'ALTER TABLE {table_name} DROP COLUMN owner_id')


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0006_seed_contracts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_owner_column, remove_owner_column),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='companyprofile',
                    name='owner',
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        db_constraint=False,
                        db_index=False,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='company_profiles',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='所属账号',
                    ),
                ),
            ],
        ),
    ]
