# Generated by Django 6.0.6 on 2026-07-17 09:09

import hashlib
from datetime import timedelta

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


def populate_report_tasks(apps, schema_editor):
    AnalysisReport = apps.get_model('tenders', 'AnalysisReport')
    ProjectTask = apps.get_model('tenders', 'ProjectTask')
    offsets = {'material': timedelta(days=3), 'guarantee': timedelta(days=2), 'deadline': timedelta(hours=6), 'action': timedelta(days=2)}

    for report in AnalysisReport.objects.select_related('tender_project').all():
        project = report.tender_project
        specs = []
        for value in report.next_actions or []:
            title = str(value or '').strip()
            if not title:
                continue
            category = 'guarantee' if '保证金' in title else 'material' if any(key in title for key in ('材料', '资质', '授权', '证书', '证明')) else 'deadline' if any(key in title for key in ('截止', '报名', '递交')) else 'action'
            specs.append((title, category))
        for value in report.missing_materials or []:
            title = str(value or '').strip()
            if title:
                specs.append((f'补齐材料：{title}', 'material'))
        if project.deadline:
            specs.append(('确认投标文件已在截止时间前完成递交', 'deadline'))

        seen = set()
        for title, category in specs:
            normalized = ''.join(title.lower().split())
            dedupe_key = f'{category}:{normalized}'
            if dedupe_key in seen:
                continue
            seen.add(dedupe_key)
            due_at = max(project.deadline - offsets[category], timezone.now()) if project.deadline else None
            ProjectTask.objects.create(
                tender_project=project,
                analysis_report=report,
                title=title,
                category=category,
                due_at=due_at,
                source_key=hashlib.sha256(dedupe_key.encode('utf-8')).hexdigest()[:40],
            )


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0010_require_existing_users_password_change'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='任务标题')),
                ('category', models.CharField(choices=[('action', '报告动作'), ('material', '材料补齐'), ('guarantee', '保证金'), ('deadline', '截止时间')], default='action', max_length=32, verbose_name='任务分类')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('completed', '已完成')], default='pending', max_length=24, verbose_name='任务状态')),
                ('due_at', models.DateTimeField(blank=True, null=True, verbose_name='计划完成时间')),
                ('source_key', models.CharField(max_length=64, verbose_name='自动任务标识')),
                ('is_auto_generated', models.BooleanField(default=True, verbose_name='报告自动生成')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('analysis_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_tasks', to='tenders.analysisreport', verbose_name='来源报告')),
                ('tender_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tenders.tenderproject', verbose_name='招标项目')),
            ],
            options={
                'verbose_name': '项目任务',
                'verbose_name_plural': '项目任务',
                'ordering': ['status', 'due_at', 'created_at'],
                'constraints': [models.UniqueConstraint(fields=('tender_project', 'source_key'), name='unique_project_auto_task')],
            },
        ),
        migrations.RunPython(populate_report_tasks, migrations.RunPython.noop),
    ]
