# Generated by Django 6.0.6 on 2026-07-17 09:37

from datetime import timedelta

from django.db import migrations, models
from django.utils import timezone


def populate_reminder_times(apps, schema_editor):
    ProjectTask = apps.get_model('tenders', 'ProjectTask')
    now = timezone.now()
    for task in ProjectTask.objects.filter(due_at__isnull=False, remind_at__isnull=True):
        task.remind_at = max(task.due_at - timedelta(days=1), now)
        task.save(update_fields=['remind_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0011_projecttask'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttask',
            name='assignee_name',
            field=models.CharField(blank=True, max_length=80, verbose_name='负责人'),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='remind_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='提醒时间'),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='reminder_read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='提醒已读时间'),
        ),
        migrations.RunPython(populate_reminder_times, migrations.RunPython.noop),
    ]
