export const demoCompany = {
  id: 1,
  name: '华东数智工程有限公司',
  main_business: '政企数字化平台建设、系统集成、软件开发、数据治理、智能运维服务。',
  service_regions: '华东、华中、全国重点省会城市。',
  max_project_amount: 50000000,
  forbidden_conditions: '纯垫资项目不投，回款周期超过12个月需升级审批，异地长期驻场需复核。',
  qualifications: [
    {
      name: 'ISO9001质量管理体系认证',
      certificate_no: 'ISO-2026-001',
      issuer: '认证机构',
      valid_until: '2028-12-31',
    },
    {
      name: '信息系统建设和服务能力证书',
      certificate_no: 'CS-2026-032',
      issuer: '行业协会',
      valid_until: '2029-06-30',
    },
  ],
  experiences: [
    {
      name: '智慧园区数字化平台建设项目',
      industry: '政企信息化',
      amount: 6800000,
      client_name: '某高新区管委会',
      completed_at: '2025-11-20',
      description: '完成园区数据中台、企业服务门户、运维监控和移动端应用建设。',
    },
    {
      name: '政务数据治理与共享交换项目',
      industry: '数据治理',
      amount: 4200000,
      client_name: '某市大数据中心',
      completed_at: '2024-09-16',
      description: '完成数据目录、质量规则、共享接口和安全审计模块交付。',
    },
  ],
}

export const demoProjects = [
  {
    id: 1,
    name: '智慧园区数字化平台建设项目',
    decision: 'recommended',
    decision_label: '推荐投标',
    match_score: 92,
    risk_level: '低',
    status: 'analyzed',
    status_label: '已分析',
    pendingStatus: 'analyzed',
    project_type: '软件信息化',
    company_name: demoCompany.name,
    budget_amount: 4800000,
    created_at: '2026-06-26T09:00:00',
    report_id: 1,
  },
  {
    id: 2,
    name: '政务数据治理服务采购项目',
    decision: 'cautious',
    decision_label: '谨慎投标',
    match_score: 78,
    risk_level: '高',
    status: 'pending',
    status_label: '待复核',
    pendingStatus: 'pending',
    project_type: '数据服务',
    company_name: demoCompany.name,
    budget_amount: 2200000,
    created_at: '2026-06-27T10:00:00',
    report_id: 2,
  },
  {
    id: 3,
    name: '企业门户与统一身份认证升级项目',
    decision: 'recommended',
    decision_label: '推荐投标',
    match_score: 88,
    risk_level: '中',
    status: 'recommended',
    status_label: '推荐报名',
    pendingStatus: 'recommended',
    project_type: '软件开发',
    company_name: demoCompany.name,
    budget_amount: 960000,
    created_at: '2026-06-25T08:00:00',
    report_id: 3,
  },
]

export const demoSummary = {
  total: 3,
  recommended: 2,
  cautious: 1,
  not_recommended: 0,
  high_risk: 1,
}

export const demoReport = {
  id: 1,
  decision: 'recommended',
  decision_label: '推荐投标',
  match_score: 92,
  summary: '项目方向与企业数字化平台建设能力高度匹配，预算规模适中，建议进入报名与方案准备阶段。',
  risks: [
    { level: '低', title: '资质要求明确', description: '现有资质基本覆盖要求，需复核证书有效期。' },
    { level: '中', title: '材料完整性', description: '原厂授权函和项目经理证明材料需要提前准备。' },
  ],
  missing_materials: ['原厂授权函', '项目经理近三个月社保证明'],
  next_actions: ['确认报名截止时间', '补齐授权函', '整理类似业绩证明', '安排技术方案初稿'],
  created_at: '2026-06-27T10:30:00',
  project: {
    id: 1,
    name: '智慧园区数字化平台建设项目',
    procurement_method: '公开招标',
    project_type: '软件信息化',
    region: '江苏',
    budget_amount: 4800000,
    status: 'analyzed',
    source_text: '演示标书文本',
    company: { id: 1, name: demoCompany.name },
  },
  qualification_match: {
    matched: ['ISO9001质量管理体系认证', '信息系统建设和服务能力证书'],
    missing: ['原厂授权函'],
  },
  experience_match: {
    matched: ['智慧园区数字化平台建设项目'],
    note: '历史业绩与本项目场景接近。',
  },
  material_checklist: ['营业执照', '资质证书', '类似业绩合同', '授权函', '项目团队简历'],
  agent_trace: ['解析招标要求', '匹配企业资质', '识别风险条款', '生成投标建议'],
  raw_report: {},
}
