export const demoCompany = {
  id: 1,
  name: '华东数智工程有限公司',
  main_business: '政企数字化平台建设、系统集成、软件开发、数据治理、智能运维服务。',
  service_regions: '华东、华中、全国重点省会城市。',
  max_project_amount: 50000000,
  forbidden_conditions: '纯垫资项目不投，回款周期超过12个月需升级审批，异地长期驻场需复核。',
  qualifications: [
    {
      name: 'ISO9001质量管理体系认证',
      certificate_no: 'ISO-2026-001',
      issuer: '中国质量认证中心',
      valid_until: '2028-12-31',
    },
    {
      name: '信息系统建设和服务能力证书（ITSS）',
      certificate_no: 'ITSS-2026-032',
      issuer: '中国电子技术标准化研究院',
      valid_until: '2029-06-30',
    },
    {
      name: '信息安全管理体系认证（ISO27001）',
      certificate_no: 'ISMS-2025-018',
      issuer: '方圆标志认证集团',
      valid_until: '2028-03-31',
    },
    {
      name: '高新技术企业认定证书',
      certificate_no: 'GXQ-2024-1138',
      issuer: '国家科学技术部',
      valid_until: '2027-12-31',
    },
  ],
  experiences: [
    {
      name: '某高新区智慧园区数字化平台建设项目',
      industry: '政企信息化',
      amount: 6800000,
      client_name: '华东高新技术产业开发区管委会',
      completed_at: '2025-11-20',
      description: '完成园区数据中台、企业服务门户、运维监控和移动端应用建设，已通过验收。',
    },
    {
      name: '某市政务数据治理与共享交换项目',
      industry: '数据治理',
      amount: 4200000,
      client_name: '某市大数据管理中心',
      completed_at: '2024-09-16',
      description: '完成数据目录编制、质量规则配置、共享接口和安全审计模块交付。',
    },
    {
      name: '某省厅统一身份认证及权限管理系统',
      industry: '软件开发',
      amount: 2800000,
      client_name: '某省人力资源和社会保障厅',
      completed_at: '2024-04-30',
      description: '覆盖单点登录、角色权限、操作审计，接入厅级业务系统12套。',
    },
    {
      name: '某央企集团信息化运维服务项目',
      industry: '运维服务',
      amount: 3600000,
      client_name: '某央企集团信息化部',
      completed_at: '2025-06-28',
      description: '提供7×24小时运维支持、巡检和应急响应服务，覆盖华东三省一市。',
    },
  ],
}

export const demoProjects = [
  {
    id: 1,
    name: '某高新区智慧园区数字化平台建设项目',
    decision: 'recommended',
    decision_label: '推荐投标',
    match_score: 92,
    risk_level: '低',
    status: 'analyzed',
    status_label: '已分析',
    pendingStatus: 'analyzed',
    project_type: '软件信息化',
    company_name: demoCompany.name,
    budget_amount: 4800000,
    region: '江苏',
    procurement_method: '公开招标',
    deadline: '2026-09-18T09:30:00',
    created_at: '2026-07-26T09:00:00',
    report_id: 1,
    pending_task_count: 4,
    overdue_task_count: 0,
  },
  {
    id: 2,
    name: '某市政务数据治理服务采购项目',
    decision: 'cautious',
    decision_label: '谨慎投标',
    match_score: 76,
    risk_level: '高',
    status: 'pending',
    status_label: '待复核',
    pendingStatus: 'pending',
    project_type: '数据服务',
    company_name: demoCompany.name,
    budget_amount: 2200000,
    region: '浙江',
    procurement_method: '竞争性谈判',
    deadline: '2026-08-25T14:00:00',
    created_at: '2026-07-27T10:00:00',
    report_id: 2,
    pending_task_count: 3,
    overdue_task_count: 1,
  },
  {
    id: 3,
    name: '某省厅企业门户与统一身份认证升级',
    decision: 'recommended',
    decision_label: '推荐投标',
    match_score: 88,
    risk_level: '中',
    status: 'recommended',
    status_label: '推荐报名',
    pendingStatus: 'recommended',
    project_type: '软件开发',
    company_name: demoCompany.name,
    budget_amount: 960000,
    region: '上海',
    procurement_method: '单一来源',
    deadline: '2026-09-05T09:00:00',
    created_at: '2026-07-25T08:00:00',
    report_id: 3,
    pending_task_count: 2,
    overdue_task_count: 0,
  },
  {
    id: 4,
    name: '某央企集团信息化运维服务续签项目',
    decision: 'recommended',
    decision_label: '建议投标',
    match_score: 95,
    risk_level: '低',
    status: 'recommended',
    status_label: '推荐报名',
    pendingStatus: 'recommended',
    project_type: '运维服务',
    company_name: demoCompany.name,
    budget_amount: 3600000,
    region: '上海',
    procurement_method: '竞争性磋商',
    deadline: '2026-09-12T10:00:00',
    created_at: '2026-07-24T14:00:00',
    report_id: 4,
    pending_task_count: 1,
    overdue_task_count: 0,
  },
  {
    id: 5,
    name: '某市社会治理综合指挥中心建设项目',
    decision: 'cautious',
    decision_label: '谨慎评估',
    match_score: 68,
    risk_level: '中',
    status: 'pending',
    status_label: '待分析',
    pendingStatus: 'pending',
    project_type: '系统集成',
    company_name: demoCompany.name,
    budget_amount: 18500000,
    region: '安徽',
    procurement_method: '公开招标',
    deadline: '2026-09-30T09:30:00',
    created_at: '2026-07-23T08:30:00',
    report_id: null,
    pending_task_count: 0,
    overdue_task_count: 0,
  },
]

export const demoSummary = {
  total: 5,
  recommended: 3,
  cautious: 2,
  not_recommended: 0,
  high_risk: 1,
}

export const demoReport = {
  id: 1,
  decision: 'recommended',
  decision_label: '推荐投标',
  match_score: 92,
  summary:
    '项目方向与企业智慧园区及政企数字化能力高度匹配，预算规模适中，资质基本满足门槛要求。建议确认授权函材料后尽快进入报名与方案准备阶段。',
  risks: [
    {
      level: '低',
      type: '资质匹配',
      title: '核心资质齐备',
      description: '现有ISO9001和ITSS证书基本覆盖资质要求，需提前确认证书在投标截止日前有效。',
    },
    {
      level: '中',
      type: '材料完整性',
      title: '原厂授权函待补',
      description: '招标文件要求提供关键软硬件的原厂授权函，需联系厂商提前安排，通常需要5~7个工作日。',
    },
    {
      level: '低',
      type: '商务风险',
      title: '付款条件标准',
      description: '合同约定验收后支付70%、质保期满支付30%，付款节奏属行业正常水平。',
    },
  ],
  missing_materials: ['原厂授权函（核心软硬件供应商）', '项目经理近三个月社保缴纳证明'],
  next_actions: [
    '确认报名截止时间并完成报名登记',
    '联系软硬件供应商申请原厂授权函',
    '准备项目经理社保证明及相关资质复印件',
    '组织技术方案初稿评审',
    '制定投标报价策略',
  ],
  created_at: '2026-07-27T10:30:00',
  project: {
    id: 1,
    name: '某高新区智慧园区数字化平台建设项目',
    procurement_method: '公开招标',
    project_type: '软件信息化',
    region: '江苏',
    budget_amount: 4800000,
    deadline: '2026-09-18T09:30:00',
    status: 'analyzed',
    source_text: '演示标书文本',
    company: { id: 1, name: demoCompany.name },
  },
  qualification_match: {
    status: 'partial',
    score: 88,
    matched: ['ISO9001质量管理体系认证', '信息系统建设和服务能力证书（ITSS）', '高新技术企业认定证书'],
    missing: ['原厂授权函（关键软硬件供应商）'],
  },
  experience_match: {
    score: 92,
    summary: '企业具备智慧园区类项目完整交付经验，与本项目场景高度吻合。',
    matched_cases: [
      '华东高新区智慧园区数字化平台（680万，2025年完工）',
      '某央企集团信息化运维服务（360万，2025年完工）',
    ],
  },
  review_summary: {
    review_level: '可推进',
    material_status: '存在少量材料缺口',
    average_dimension_score: 87,
    high_risk_count: 0,
    material_required_count: 5,
    material_missing_count: 2,
  },
  scoring_breakdown: [
    { dimension: '资质匹配', score: 88, weight: '35%', comment: '核心资质齐全，原厂授权函需补充。' },
    { dimension: '业绩支撑', score: 92, weight: '25%', comment: '智慧园区类业绩直接匹配，评分有力。' },
    { dimension: '风险可控', score: 85, weight: '25%', comment: '无高风险条款，付款条件正常。' },
    { dimension: '技术响应', score: 82, weight: '15%', comment: '平台建设与数字化能力与项目契合。' },
  ],
  key_findings: [
    '项目方向与企业主营业务高度吻合，胜率较高',
    '原厂授权函是唯一材料缺口，需优先跟进',
    '评分标准偏向技术与业绩，企业具备明显优势',
    '预算480万，处于企业可承接范围内',
  ],
  material_checklist: [
    { category: '主体材料', name: '营业执照（三证合一）', status: 'ready' },
    { category: '资质材料', name: 'ISO9001质量管理体系认证', status: 'ready' },
    { category: '资质材料', name: '信息系统建设和服务能力证书', status: 'ready' },
    { category: '资格材料', name: '原厂授权函（核心软硬件）', status: 'missing' },
    { category: '业绩材料', name: '类似项目合同及验收报告', status: 'required' },
    { category: '人员材料', name: '项目经理资质及社保证明', status: 'required' },
    { category: '财务材料', name: '近三年财务审计报告', status: 'required' },
  ],
  agent_trace: [
    { agent: '文档解析Agent', status: 'completed' },
    { agent: '关键信息抽取Agent', status: 'completed' },
    { agent: '资质匹配Agent', status: 'completed' },
    { agent: '风险分析Agent', status: 'completed' },
    { agent: '决策建议Agent', status: 'completed' },
  ],
  raw_report: {
    highest_limit_amount: 4800000,
  },
}
